cmake_minimum_required(VERSION 3.24)
project(ClubV3Example LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_path(CLUB_SDK clubplatform/extension_v3.h REQUIRED)
find_package(nlohmann_json 3.7 CONFIG REQUIRED)
add_library(sample MODULE module.cpp)
target_include_directories(sample PRIVATE ${CLUB_SDK})
target_link_libraries(sample PRIVATE nlohmann_json::nlohmann_json)
set_target_properties(sample PROPERTIES PREFIX "" CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
